I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 252, in script
    jump final_neutro
ScriptError: could not find label 'final_neutro'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 252, in script
    jump final_neutro
  File "C:\Users\brubr\Desktop\renpy-8.3.7-sdk\renpy\ast.py", line 1712, in execute
    rv = renpy.game.script.lookup(target)
  File "C:\Users\brubr\Desktop\renpy-8.3.7-sdk\renpy\script.py", line 1103, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'final_neutro'.

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.7.25031702
Impressionismo 1.0
Thu May  8 23:26:25 2025
